source "http://rubygems.org"

gem 'dm-core',                   '1.1'
gem 'dm-migrations',             '1.1'
gem 'dm-validations',            '1.1'
gem 'dm-aggregates',             '1.1'
gem 'dm-timestamps',             '1.1'
gem 'dm-types',                  '1.1'
gem 'dm-postgres-adapter',       '1.1'
#gem 'dm-pager',                  '1.1.2', :git => 'git://github.com/poeks/dm-pagination.git'
gem 'rake',                      '0.8.7'
gem 'confit',                    '1.0.1', :require => 'confit/kernel'
gem 'rack',                      '1.2.1'
gem 'sinatra-flash',             '0.3.0', :require => 'sinatra/flash'
gem 'sinatra',                   '1.2.6', :require => 'sinatra/base'
gem 'thin'
gem 'extlib'
gem 'commander',                '4.0.6'#, :require => 'commander/import'
gem 'colored',                  '~> 1.2'
gem 'chronic'