source "http://rubygems.org"

gem 'dm-core',                   '1.1'
gem 'dm-migrations',             '1.1'
gem 'dm-validations',            '1.1'
gem 'dm-aggregates',             '1.1'
gem 'dm-timestamps',             '1.1'
gem 'dm-types',                  '1.1'
gem 'dm-postgres-adapter',       '1.1'
gem 'rake',                      '0.8.7'
gem 'confit',                    '1.0.1', :require => 'confit/kernel'
gem 'extlib'
gem 'commander',                '4.0.6'
gem 'colored',                  '~> 1.2'
gem 'chronic'